#pragma once

/*----------------------------------------------------------------------------
	Low level includes.
----------------------------------------------------------------------------*/

#include "CoreMinimal.h"
#include "Containers/ContainersFwd.h"
#include "HAL/PlatformMemory.h"
#include "Misc/Char.h"
#include "Templates/EnableIf.h"
#include "Templates/AndOrNot.h"
#include "Templates/IsArithmetic.h"
#include "Templates/IsIntegral.h"
#include "Templates/IsPointer.h"
#include "Templates/IsPODType.h"
#include "Templates/IsTriviallyCopyAssignable.h"
#include "Templates/IsTriviallyCopyConstructible.h"
#include "GenericPlatform/GenericPlatformMisc.h"
#include "HAL/PlatformMisc.h"
#include "Logging/LogVerbosity.h"
#include "GenericPlatform/GenericPlatformStricmp.h"
#include "HAL/PlatformString.h"
#include "HAL/PlatformMath.h"
#include "GenericPlatform/GenericPlatformProcess.h"
#include "GenericPlatform/GenericPlatformAtomics.h"
#include "HAL/PlatformAtomics.h"
#include "GenericPlatform/GenericPlatformAffinity.h"
#include "HAL/PlatformAffinity.h"
#include "Misc/AssertionMacros.h"
#include "HAL/UnrealMemory.h"
#include "Templates/PointerIsConvertibleFromTo.h"
#include "Templates/AlignmentTemplates.h"
#include "Templates/RemoveReference.h"
#include "Templates/ChooseClass.h"
#include "Templates/TypeCompatibleBytes.h"
#include "Traits/IsContiguousContainer.h"
#include "Templates/IsTriviallyDestructible.h"
#include "Misc/CString.h"
#include "Templates/IsEnumClass.h"
#include "Templates/Less.h"
#include "Logging/LogCategory.h"
#include "Logging/LogMacros.h"
#include "UObject/UnrealNames.h"
#include "Math/NumericLimits.h"
#include "Templates/UnrealTypeTraits.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/Decay.h"
#include "Templates/Invoke.h"
#include "Templates/Function.h"
#include "Templates/MemoryOps.h"

#include "Misc/CoreDefines.h"

// Container forward declarations
#include "Containers/ContainerAllocationPolicies.h"

#include "UObject/UObjectHierarchyFwd.h"

#include "CoreGlobals.h"

/*----------------------------------------------------------------------------
	Includes.
----------------------------------------------------------------------------*/

#include "Misc/Crc.h"
#include "Templates/TypeHash.h"
#include "Containers/EnumAsByte.h"
#include "Templates/Sorting.h"
#include "Containers/Array.h"
#include "Containers/IndirectArray.h"
#include "Containers/BitArray.h"
#include "Containers/SparseArray.h"
#include "Containers/UnrealString.h"
#include "UObject/NameTypes.h"
#include "HAL/Runnable.h"
#include "HAL/RunnableThread.h"
#include "HAL/ThreadSafeCounter.h"
#include "Containers/Set.h"
#include "HAL/ThreadingBase.h"
#include "Templates/IsArray.h"
#include "Templates/RemoveExtent.h"
#include "Misc/Guid.h"
#include "Math/Color.h"
#include "Math/IntVector.h"
#include "Math/Vector.h"
#include "Math/VectorRegister.h"
#include "Math/Rotator.h"
#include "Math/Axis.h"
#include "Math/Quat.h"
#include "Math/Transform.h"
#include "Misc/EnumClassFlags.h"